# Generated by Django 2.1 on 2020-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrossReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('barcodeNumber', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('allergies', models.ManyToManyField(blank=True, to='food.Allergies')),
                ('crossReaction', models.ManyToManyField(blank=True, to='food.CrossReaction')),
                ('feature', models.ManyToManyField(blank=True, to='food.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('time', models.CharField(max_length=30)),
                ('serving', models.CharField(max_length=30)),
                ('allergies', models.ManyToManyField(blank=True, to='food.Allergies')),
                ('directions', models.ManyToManyField(blank=True, to='food.Direction')),
                ('feature', models.ManyToManyField(blank=True, to='food.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeIng',
            field=models.ManyToManyField(blank=True, to='food.RecipeIng'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasoning',
            field=models.ManyToManyField(blank=True, to='food.Seasoning'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='relatedRecipes',
            field=models.ManyToManyField(blank=True, to='food.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='warnings',
            field=models.ManyToManyField(blank=True, to='food.Warn'),
        ),
    ]
