# Generated by Django 2.2.10 on 2020-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='allergies',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='food.Allergies'),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='crossReaction',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='crossReaction',
            field=models.ManyToManyField(blank=True, to='food.CrossReaction'),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='feature',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='feature',
            field=models.ManyToManyField(blank=True, to='food.Feature'),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='relatedRecipes',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='relatedRecipes',
            field=models.ManyToManyField(blank=True, to='food.Recipe'),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='warnings',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='warnings',
            field=models.ManyToManyField(blank=True, to='food.Warn'),
        ),
    ]
