# Generated by Django 2.1.5 on 2020-10-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201023_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeing',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasoning',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
