# Generated by Django 2.1.1 on 2020-10-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20201021_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='crossReaction',
            field=models.ManyToManyField(blank=True, to='food.CrossReaction'),
        ),
    ]
